name: conQest
version: ${version}
main: ${mainClass}
description: ${description}
author: ${author}
api-version: ${apiVersion}
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}
commands:
  getchancecard:
    description: コマンドを使用したプレイヤーがチャンスカードを取得します。
    usage: /getchancecard