package jp.trap.conqest.game

import jp.trap.conqest.Main
import jp.trap.conqest.util.Partition
import net.kyori.adventure.text.Component
import net.kyori.adventure.text.format.NamedTextColor
import org.bukkit.Bukkit
import org.bukkit.Location
import java.util.*

class Field(
    val plugin: Main, val creatorId: UUID, val center: Location, val partition: Partition, val roadWidth: Double = 3.0
) {

    init {
        require(roadWidth > 0.0) { "roadWidth must be positive" }

        partition.printRoadWidth = roadWidth
    }

    fun bottom(): Int = center.blockX - partition.fieldSize.first / 2

    fun top(): Int = bottom() + partition.fieldSize.first

    fun left(): Int = center.blockZ - partition.fieldSize.second / 2

    fun right(): Int = left() + partition.fieldSize.second

    fun preview(radius: Double = Double.POSITIVE_INFINITY) {
        // TODO: preview
    }

    fun generate() {
        // TODO: generate
        Bukkit.getEntity(creatorId)?.sendMessage(Component.text("TODO: confirm", NamedTextColor.GOLD))

        with(plugin.logger) {
            info("-".repeat(40))
            info("Field generated by $creatorId")
            info("  X: ${bottom()} to ${top()}")
            info("  Z: ${left()} to ${right()}")
            partition.toString().split("\n").forEach { info(it) }
            info("-".repeat(40))
        }

    }

}
